name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: List dist folder contents
      run: ls dist/

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          sudo mkdir -p /home/ubuntu/vue-website
          sudo chown ${{ secrets.EC2_USERNAME }} /home/ubuntu/vue-website
          rsync -avz -e "ssh -i ${{ secrets.EC2_PRIVATE_KEY }}" --delete dist/ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/vue-website/
          ls /home/ubuntu/vue-website/
          sudo systemctl restart nginx
    
    - name: Check deployed files
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          echo "Contents of /home/ubuntu/vue-website:"
          ls -la /home/ubuntu/vue-website
          echo "Content of the index.html file:"
          cat /home/ubuntu/vue-website/dist/index.html



